name: Comment Commits

on:
  workflow_run:
    workflows: [CICDPipeline]
    types:
      - completed

permissions:
  contents: write

jobs:
  reports:
    name: Comment Commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Comment on Commit
        uses: actions/github-script@v7
        with:
          script: |
            const status = process.env.GITHUB_WORKFLOW_CONCLUSION;
            const sha = github.event.workflow_run.head_commit.id;  
            const ref = github.event.workflow_run.head_commit.tree_id;  
            const repo = github.repository.split('/')[1];
            const owner = github.repository.split('/')[0];
            const comment = `Pipeline Status: ${status}\nCommit: ${sha}\nBranch: ${ref}\nRepository: ${owner}/${repo}`;
            await github.rest.repos.createCommitComment({
              owner: owner,
              repo: repo,
              commit_sha: sha,
              body: comment
            });
