name: Follow-Up Workflow

on:
  workflow_run:
    workflows: [Pipeline CI] 
    types:
      - completed
permissions:
  contents: write
  id-token: write
jobs:
  reports:
    runs-on: ubuntu-latest
    steps: 
      - name: comment commit
        uses: actions/github-script@v6
        with:
          script: |
            const status = process.env.GITHUB_WORKFLOW_CONCLUSION;
            const sha = process.env.GITHUB_SHA;
            const ref = process.env.GITHUB_REF;
            const repo = process.env.GITHUB_REPOSITORY.split('/')[1];
            const owner = process.env.GITHUB_REPOSITORY.split('/')[0];
            const comment = `Pipeline Status: ${status}\nCommit: ${sha}\nBranch: ${ref}\nRepository: ${owner}/${repo}`;
            await github.rest.repos.createCommitComment({
              owner: owner,
              repo: repo,
              commit_sha: sha,
              body: comment
            });
